services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    user: "1000:1000"

    ports:
      - "8096:8096"

    volumes:
      - ../../data/jellyfin/config:/config
      - ../../data/jellyfin/cache:/cache
      - ../../media/movies:/media/movies:ro

    restart: unless-stopped